"""instance/config.py
"""
import os

DATA_USER = os.environ['DATABASE_USER']
DATA_PASS = os.environ['DATABASE_PASS']
DATA_HOST = os.environ['DATABASE_HOST']
DATA_NAME = os.environ['DATABASE_NAME']
SECRETKEY = os.environ['FLASK_SECRETKEY']

DEBUG = True
# SECRET_KEY is generated by os.urandom(24).
SECRET_KEY = SECRETKEY
STRIPE_API_KEY = ''


SQLALCHEMY_DATABASE_URI = 'postgresql+psycopg2://{user}:{password}@{host}/{name}'.format(**{
    'user': DATA_USER,
    'password': DATA_PASS,
    'host': DATA_HOST,
    'name': DATA_NAME
}) or os.environ.get('DATABASE_URL')

SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = True
